# poetry build
# poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo python3 -m pip install --upgrade pip
        sudo apt-cache install libicu-dev
    - name: Install Poetry  # https://github.com/marketplace/actions/python-poetry-action
      uses: abatilo/actions-poetry@v1.5.0
      with:
        # python_version: 3.8.0
        # poetry_version: 0.12.17
        python_version: 3.6.7
        poetry_version: 1.0.5
        # working_directory: ./working_dir # Optional, defaults to '.'
        args: install

    - name: Lint with flake8
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.7
        poetry_version: 1.0.5
        args: run python -m flake8 . --count --exit-zero --max-complexity=35 --ignore=E501,F401,E302,W292,F811,F841 --statistics

    - name: Test with pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.7
        poetry_version: 1.0.5
        args: run python -m pytest tests

    - name: Build Python package
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.7
        poetry_version: 1.0.5
        args: build

    - name: Publish to PyPI
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.7
        poetry_version: 1.0.5
        # args: publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}